# Consolidate Artifacts Job Template
# Downloads artifacts from all platform build jobs and consolidates into single dist/ folder
parameters:
  - name: oneBranchType
    type: string
    default: 'Official'

jobs:
  - job: ConsolidateArtifacts
    displayName: 'Consolidate All Platform Artifacts'
    dependsOn:
      - BuildWindowsWheels
      - BuildMacOSWheels
      - BuildLinuxWheels
    condition: succeeded()
    
    pool:
      type: linux
      isCustom: true
      name: Azure Pipelines
      vmImage: 'ubuntu-latest'
    
    variables:
      ob_outputDirectory: '$(Build.ArtifactStagingDirectory)'
    
    steps:
      - checkout: none  # No source code needed for consolidation
      
      # Download ALL artifacts from all platform build jobs
      # This downloads all Windows, macOS, and Linux artifacts (27 total)
      - task: DownloadPipelineArtifact@2
        displayName: 'Download All Platform Artifacts'
        inputs:
          buildType: 'current'
          targetPath: '$(Pipeline.Workspace)/artifacts'
      
      # Consolidate all wheels into single dist/ directory
      - bash: |
          set -e
          echo "Creating consolidated dist directory..."
          mkdir -p $(ob_outputDirectory)/dist
          
          echo "Finding all wheel files from all artifacts..."
          find $(Pipeline.Workspace)/artifacts -name "*.whl" -exec ls -lh {} \;
          
          echo ""
          echo "Copying all wheels to consolidated dist/..."
          find $(Pipeline.Workspace)/artifacts -name "*.whl" -exec cp -v {} $(ob_outputDirectory)/dist/ \;
          
          echo ""
          echo "Consolidation complete! Total wheels:"
          ls -lh $(ob_outputDirectory)/dist/
          echo ""
          echo "Total wheel count: $(ls -1 $(ob_outputDirectory)/dist/*.whl 2>/dev/null | wc -l)"
        displayName: 'Consolidate wheels from all platforms'
      
      # Optional: Consolidate native bindings for reference
      - bash: |
          set -e
          echo "Creating bindings directory structure..."
          mkdir -p $(ob_outputDirectory)/bindings
          
          echo "Copying all bindings from all artifacts..."
          find $(Pipeline.Workspace)/artifacts -type d -name "bindings" -exec cp -rv {}/* $(ob_outputDirectory)/bindings/ \; 2>/dev/null || true
          
          echo "Bindings consolidation complete!"
        displayName: 'Consolidate native bindings (optional)'
        continueOnError: true
      
      # Optional: Consolidate Windows symbols
      - bash: |
          set -e
          if find $(Pipeline.Workspace)/artifacts -type d -name "symbols" | grep -q .; then
            echo "Copying Windows symbols..."
            mkdir -p $(ob_outputDirectory)/symbols
            find $(Pipeline.Workspace)/artifacts -type d -name "symbols" -exec cp -rv {}/* $(ob_outputDirectory)/symbols/ \;
            echo "Symbols consolidation complete!"
          else
            echo "No Windows symbols found (expected for NonOfficial builds)"
          fi
        displayName: 'Consolidate Windows symbols (optional)'
        continueOnError: true
      
      # Verify consolidation
      - bash: |
          echo "=========================================="
          echo "Consolidation Summary"
          echo "=========================================="
          echo ""
          echo "Wheels in dist/:"
          ls -lh $(ob_outputDirectory)/dist/*.whl || echo "No wheels found!"
          echo ""
          echo "Total wheels: $(ls -1 $(ob_outputDirectory)/dist/*.whl 2>/dev/null | wc -l)"
          echo ""
          if [ -d "$(ob_outputDirectory)/bindings" ]; then
            echo "Bindings directory:"
            find $(ob_outputDirectory)/bindings -type f | head -20
          fi
          echo ""
          echo "=========================================="
        displayName: 'Verify consolidation'
      
      # Publish consolidated artifacts
      - task: PublishPipelineArtifact@1
        displayName: 'Publish Consolidated Artifacts'
        inputs:
          targetPath: '$(ob_outputDirectory)'
          artifact: 'drop_Build_ConsolidateArtifacts'
          publishLocation: 'pipeline'
