name: build-and-release-pipeline

jobs:
- job: BuildWheel
  pool:
    vmImage: 'windows-latest'
  
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.13'
      addToPath: true
      githubToken: $(GITHUB_TOKEN)
    displayName: 'Use Python 3.13'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install build dependencies'

  - script: |
      python setup.py bdist_wheel
    displayName: 'Build .whl file'

  - task: PublishBuildArtifacts@1
    inputs:
        PathtoPublish: 'dist'
        ArtifactName: 'mssql-python'
        publishLocation: 'Container'
    displayName: 'Publish Artifact'

  - task: EsrpRelease@7
    inputs:
      ConnectedServiceName: 'mssql-python-service'
      keyvaultname: mssqlpythonKey
      authcertname: 'ESRP-Release-mssql-python-auth'
      signcertname: 'ESRP-Release-mssql-python-Sign2'
      clientid: 'a0d18a38-fde1-4ba7-92e1-15be16cb6a8e'
      Intent: 'PackageDistribution'
      ContentType: 'PyPi'
      ContentSource: 'Folder'
      FolderLocation: '$(System.DefaultWorkingDirectory)/dist'
      WaitForReleaseCompletion: true
      Owners: 'enumittal@microsoft.com'
      Approvers: 'enumittal@microsoft.com'
      ServiceEndpointUrl: 'https://api.esrp.microsoft.com'
      MainPublisher: 'ESRPRELPACMAN'
      DomainTenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47'
    displayName: 'ESRP Release'
