# Pipeline name shown in ADO UI
name: build-pyd-pipeline

# Trigger the pipeline on pushes to these branches
trigger:
  branches:
    include:
      - main
      - dev

# Use Microsoft-hosted Windows VM
pool:
  vmImage: 'windows-latest'

jobs:
- job: BuildPYDs
  displayName: Build PYD files across all Python versions + architectures

  # Strategy matrix to build all combinations
  strategy:
    matrix:
      # Python 3.11
      py311_x64:
        pythonVersion: '3.11'       # Host Python version
        shortPyVer: '311'           # Used in filenames like cp311
        architecture: 'x64'         # Host Python architecture
        targetArch: 'x64'           # Target architecture to pass to build.bat
      py311_x86:
        pythonVersion: '3.11'
        shortPyVer: '311'
        architecture: 'x86'
        targetArch: 'x86'
      py311_arm64:
        pythonVersion: '3.11'
        shortPyVer: '311'
        architecture: 'x64'         # No arm64 Python, use x64 host
        targetArch: 'arm64'

      # Python 3.12
      py312_x64:
        pythonVersion: '3.12'
        shortPyVer: '312'
        architecture: 'x64'
        targetArch: 'x64'
      py312_x86:
        pythonVersion: '3.12'
        shortPyVer: '312'
        architecture: 'x86'
        targetArch: 'x86'
      py312_arm64:
        pythonVersion: '3.12'
        shortPyVer: '312'
        architecture: 'x64'
        targetArch: 'arm64'

      # Python 3.13
      py313_x64:
        pythonVersion: '3.13'
        shortPyVer: '313'
        architecture: 'x64'
        targetArch: 'x64'
      py313_x86:
        pythonVersion: '3.13'
        shortPyVer: '313'
        architecture: 'x86'
        targetArch: 'x86'
      py313_arm64:
        pythonVersion: '3.13'
        shortPyVer: '313'
        architecture: 'x64'
        targetArch: 'arm64'

  steps:
    # Use correct Python version and architecture for the current job
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
        architecture: '$(architecture)'
        addToPath: true
      displayName: 'Use Python $(pythonVersion) ($(architecture))'

    # Install required packages: pip, CMake, pybind11
    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install cmake pybind11
      displayName: 'Install dependencies'

    # Build the PYD file by calling build.bat
    - script: |
        echo "Python Version: $(pythonVersion)"
        echo "Short Tag: $(shortPyVer)"
        echo "Architecture: Host=$(architecture), Target=$(targetArch)"

        cd "$(Build.SourcesDirectory)\mssql_python\pybind"

        REM Optional: override lib path if building for ARM64
        if "$(targetArch)"=="arm64" (
          echo Using arm64-specific Python library...
          set PYTHON_LIBRARY_PATH=$(Build.SourcesDirectory)\mssql_python\pybind\python_libs\arm64\python$(shortPyVer).lib
        )

        call build.bat $(targetArch)

        cd ..\..
      displayName: 'Build PYD for $(targetArch)'

    # Copy the built .pyd file to staging folder for artifacts
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)\mssql_python\pybind\build\$(targetArch)\py$(shortPyVer)\Release'
        Contents: 'ddbc_bindings.cp$(shortPyVer)-*.pyd'
        TargetFolder: '$(Build.ArtifactStagingDirectory)\all-pyds\$(shortPyVer)\$(targetArch)'
      displayName: 'Collect PYD files'

    # Publish the collected .pyd file(s) as build artifacts
    - task: PublishBuildArtifacts@1
      condition: succeededOrFailed()
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)\all-pyds'
        ArtifactName: 'mssql-python-all-pyds'
        publishLocation: 'Container'
      displayName: 'Publish PYD artifacts'
