name: build-pyd-pipeline

variables:
  pythonVersions: '3.11 3.12 3.13'
  architectures: 'x64 arm64 x86'

jobs:
- job: BuildAllPyds
  strategy:
    matrix:
      py311_x64:
        pythonVersion: '3.11'
        architecture: 'x64'
        shortPyVer: '311'
        targetArch: 'x64'
      py311_x86:
        pythonVersion: '3.11'
        architecture: 'x86'
        shortPyVer: '311'
        targetArch: 'x86'
      py311_arm64:
        pythonVersion: '3.11'
        architecture: 'x64'  # host Python
        shortPyVer: '311'
        targetArch: 'arm64'
      py312_x64:
        pythonVersion: '3.12'
        architecture: 'x64'
        shortPyVer: '312'
        targetArch: 'x64'
      py312_x86:
        pythonVersion: '3.12'
        architecture: 'x86'
        shortPyVer: '312'
        targetArch: 'x86'
      py312_arm64:
        pythonVersion: '3.12'
        architecture: 'x64'
        shortPyVer: '312'
        targetArch: 'arm64'
      py313_x64:
        pythonVersion: '3.13'
        architecture: 'x64'
        shortPyVer: '313'
        targetArch: 'x64'
      py313_x86:
        pythonVersion: '3.13'
        architecture: 'x86'
        shortPyVer: '313'
        targetArch: 'x86'
      py313_arm64:
        pythonVersion: '3.13'
        architecture: 'x64'
        shortPyVer: '313'
        targetArch: 'arm64'

  pool:
    vmImage: 'windows-latest'

  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
        architecture: '$(architecture)'
        addToPath: true
      displayName: 'Use Python $(pythonVersion) ($(architecture))'

    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install cmake pybind11
      displayName: 'Install dependencies'

    - script: |
        echo "Working directory: %CD%"
        echo "Build source directory: $(Build.SourcesDirectory)"
        echo "Python version: $(pythonVersion) - $(shortPyVer)"
        echo "Target Architecture: $(targetArch)"

        cd "$(Build.SourcesDirectory)\mssql_python\pybind"
        dir
        call build.bat $(targetArch)
        cd ..\..
      displayName: 'Build PYD for $(targetArch)'

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)\mssql_python\pybind\build\$(targetArch)\py$(shortPyVer)\Release'
        Contents: 'ddbc_bindings.cp$(shortPyVer)-*.pyd'
        TargetFolder: '$(Build.ArtifactStagingDirectory)\all-pyds\$(shortPyVer)\$(targetArch)'
      displayName: 'Collect PYD files'

    - task: PublishBuildArtifacts@1
      condition: succeededOrFailed()
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)\all-pyds'
        ArtifactName: 'mssql-python-all-pyds'
        publishLocation: 'Container'
      displayName: 'Publish PYD artifacts'
