from enum import Enum

class ConstantsODBC(Enum):
    SQL_HANDLE_ENV = 1
    SQL_HANDLE_DBC = 2
    SQL_HANDLE_STMT = 3
    SQL_SUCCESS = 0
    SQL_SUCCESS_WITH_INFO = 1
    SQL_NO_DATA = 100
    SQL_STILL_EXECUTING = 2
    SQL_NTS = -3
    SQL_DRIVER_NOPROMPT = 0
    SQL_ATTR_ASYNC_DBC_EVENT = 119
    SQL_IS_INTEGER = -6
    SQL_ATTR_ASYNC_DBC_FUNCTIONS_ENABLE = 117
    SQL_OV_ODBC3_80 = 380
    SQL_ATTR_ODBC_VERSION = 200
    SQL_ATTR_ASYNC_ENABLE = 4
    SQL_ATTR_ASYNC_STMT_EVENT = 29
    SQL_ERROR = -1
    SQL_INVALID_HANDLE = -2
    SQL_NULL_HANDLE = 0
    SQL_OV_ODBC3 = 3
    SQL_COMMIT = 0
    SQL_ROLLBACK = 1

class ConstantsSQLSTATE(Enum):
    GENERAL_WARNING = "01000"
    OPTION_VALUE_CHANGED = "01S02"
    GENERAL_ERROR = "HY000"
    MEMORY_ALLOCATION_ERROR = "HY001"
    INVALID_USE_OF_NULL_POINTER = "HY009"
    FUNCTION_SEQUENCE_ERROR = "HY010"
    MEMORY_MANAGEMENT_ERROR = "HY013"
    INVALID_ATTRIBUTE_VALUE = "HY024"
    INVALID_STRING_OR_BUFFER_LENGTH = "HY090"
    INVALID_ATTRIBUTE_OPTION_IDENTIFIER = "HY092"
    CONNECTION_SUSPENDED = "HY117"
    OPTIONAL_FEATURE_NOT_IMPLEMENTED = "HYC00"
