# macOS Single Configuration Stage Template
# Builds Python wheel for a specific Python version (universal2 binary)
parameters:
  - name: stageName
    type: string
  - name: jobName
    type: string
    default: 'BuildWheel'
  - name: pythonVersion
    type: string
  - name: shortPyVer
    type: string
  - name: oneBranchType
    type: string
    default: 'Official'
  - name: signingEnabled
    type: boolean
    default: true
  - name: buildConfiguration
    type: string
    default: 'Release'

stages:
  - stage: ${{ parameters.stageName }}
    displayName: 'Build macOS Python ${{ parameters.pythonVersion }}'
    jobs:
      - job: ${{ parameters.jobName }}
        displayName: 'Build Wheel - Python ${{ parameters.pythonVersion }} universal2'
        pool:
          type: linux
          isCustom: true
          name: Azure Pipelines
          vmImage: 'macOS-14'
        timeoutInMinutes: 120
        
        variables:
          ob_outputDirectory: '$(Build.ArtifactStagingDirectory)'
          LinuxContainerImage: 'onebranch.azurecr.io/linux/ubuntu-2204:latest'
          pythonVersion: ${{ parameters.pythonVersion }}
          shortPyVer: ${{ parameters.shortPyVer }}
        
        steps:
          - checkout: self
            fetchDepth: 0
          
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '${{ parameters.pythonVersion }}'
            displayName: 'Use Python ${{ parameters.pythonVersion }}'
          
          - bash: |
              set -e
              echo "Python version:"
              python3 --version
              echo "Architecture:"
              uname -m
            displayName: 'Verify Python installation'
          
          - bash: |
              set -e
              echo "Installing Python dependencies..."
              python3 -m pip install --upgrade pip
              python3 -m pip install setuptools wheel pybind11 pytest pyodbc
              echo "Dependencies installed successfully"
            displayName: 'Install Python dependencies'
          
          - bash: |
              set -e
              echo "Building native bindings..."
              cd mssql_python/pybind
              bash build.sh
            displayName: 'Build native bindings'
          
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)/mssql_python'
              Contents: '*.dylib'
              TargetFolder: '$(ob_outputDirectory)/bindings/macOS'
            displayName: 'Copy dylib files'
          
          - bash: |
              set -e
              echo "Building Python wheel..."
              python3 setup.py bdist_wheel
            displayName: 'Build wheel package'
          
          - bash: |
              set -e
              echo "Running pytests to validate bindings..."
              python3 -m pytest -v || echo "Tests failed or SQL Server not available"
            displayName: 'Run pytests'
            continueOnError: true
            env:
              DB_CONNECTION_STRING: 'Driver=ODBC Driver 18 for SQL Server;Server=tcp:127.0.0.1,1433;Database=master;Uid=SA;Pwd=$(DB_PASSWORD);TrustServerCertificate=yes'
          
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)/dist'
              Contents: '*.whl'
              TargetFolder: '$(ob_outputDirectory)/wheels'
            displayName: 'Copy wheel files'
          
          # Explicit publish with OneBranch-compliant artifact name
          - task: PublishPipelineArtifact@1
            displayName: 'Publish macOS Artifacts'
            inputs:
              targetPath: '$(ob_outputDirectory)'
              artifact: 'drop_${{ parameters.stageName }}_${{ parameters.jobName }}'
              publishLocation: 'pipeline'
          
          # Malware scanning
          - template: ../steps/malware-scanning-step.yml@self
            parameters:
              scanPath: '$(ob_outputDirectory)'
              artifactType: 'dll'
          
          # ESRP Code Signing (Official builds only)
          - ${{ if and(eq(parameters.signingEnabled, true), eq(parameters.oneBranchType, 'Official')) }}:
              - template: /OneBranchPipelines/steps/compound-esrp-code-signing-step.yml@self
                parameters:
                  appRegistrationClientId: '$(SigningAppRegistrationClientId)'
                  appRegistrationTenantId: '$(SigningAppRegistrationTenantId)'
                  artifactType: 'dll'
                  authAkvName: '$(SigningAuthAkvName)'
                  authSignCertName: '$(SigningAuthSignCertName)'
                  esrpClientId: '$(SigningEsrpClientId)'
                  esrpConnectedServiceName: '$(SigningEsrpConnectedServiceName)'
                  signPath: '$(ob_outputDirectory)/bindings/macOS'
              
              - template: /OneBranchPipelines/steps/compound-esrp-code-signing-step.yml@self
                parameters:
                  appRegistrationClientId: '$(SigningAppRegistrationClientId)'
                  appRegistrationTenantId: '$(SigningAppRegistrationTenantId)'
                  artifactType: 'whl'
                  authAkvName: '$(SigningAuthAkvName)'
                  authSignCertName: '$(SigningAuthSignCertName)'
                  esrpClientId: '$(SigningEsrpClientId)'
                  esrpConnectedServiceName: '$(SigningEsrpConnectedServiceName)'
                  signPath: '$(ob_outputDirectory)/wheels'
