name: build-and-release-pipeline

variables:
  - group: 'ESRP Federated Creds (AME)'


jobs:
- job: BuildWheel
  pool:
    vmImage: 'windows-latest'
  
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.13'
      addToPath: true
      githubToken: $(GITHUB_TOKEN)
    displayName: 'Use Python 3.13'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install build dependencies'

  - script: |
      python setup.py bdist_wheel
    displayName: 'Build .whl file'

  - task: PublishBuildArtifacts@1
    inputs:
        PathtoPublish: 'dist'
        ArtifactName: 'mssql-python'
        publishLocation: 'Container'
    displayName: 'Publish Artifact'

  - task: EsrpRelease@9
    displayName: 'ESRP Release'
    inputs:
      connectedservicename: '$(ESRPConnectedServiceName)'
      usemanagedidentity: true
      keyvaultname: '$(AuthAKVName)'
      signcertname: '$(AuthSignCertName)'
      clientid: '$(EsrpClientId)'
      Intent: 'PackageDistribution'
      ContentType: 'PyPI'
      ContentSource: 'Folder'
      FolderLocation: '$(System.DefaultWorkingDirectory)/dist'
      WaitForReleaseCompletion: true
      Owners: '$(owner)'
      Approvers: '$(approver)'
      ServiceEndpointUrl: 'https://api.esrp.microsoft.com'
      MainPublisher: 'ESRPRELPACMAN'
      DomainTenantId: '$(DomainTenantId)'
