# Building Wheels in MacOS
# - job: PytestOnMacOS
#   pool:
#     vmImage: 'macos-latest'

#   steps:
#   - task: UsePythonVersion@0
#     inputs:
#       versionSpec: '3.13.5'
#       addToPath: true
#     displayName: 'Use Python 3.13 on macOS'

#   - script: |
#       brew update
#       brew install cmake
#     displayName: 'Install CMake'
#   # - script: |
#   #     brew update
#   #     brew install docker colima

#   #     # Start Colima with extra resources
#   #     colima start --cpu 4 --memory 8 --disk 50

#   #     # Optional: set Docker context (usually automatic)
#   #     docker context use colima >/dev/null || true

#   #     # Confirm Docker is operational
#   #     docker version
#   #     docker ps
#   #   displayName: 'Install and start Colima-based Docker'

#   # - script: |
#   #     # Pull and run SQL Server container
#   #     docker pull mcr.microsoft.com/mssql/server:2022-latest
#   #     docker run \
#   #       --name sqlserver \
#   #       -e ACCEPT_EULA=Y \
#   #       -e MSSQL_SA_PASSWORD="${DB_PASSWORD}" \
#   #       -p 1433:1433 \
#   #       -d mcr.microsoft.com/mssql/server:2022-latest

#   #     # Starting SQL Server container…
#   #     for i in {1..30}; do
#   #       docker exec sqlserver \
#   #         /opt/mssql-tools18/bin/sqlcmd \
#   #         -S localhost \
#   #         -U SA \
#   #         -P "$DB_PASSWORD" \
#   #         -C -Q "SELECT 1" && break
#   #       sleep 2
#   #     done
#   #   displayName: 'Pull & start SQL Server (Docker)'
#   #   env:
#   #     DB_PASSWORD: $(DB_PASSWORD)

#   - script: |
#       python -m pip install --upgrade pip
#       pip install -r requirements.txt
#     displayName: 'Install Python dependencies'
#   - script: |
#       cd mssql_python/pybind
#       ./build.sh
#     displayName: 'Build pybind bindings (.so)'
#   - script: |
#       echo "Build successful, running tests now"
#       python -m pytest -v --junitxml=test-results.xml --cov=. --cov-report=xml --capture=tee-sys --cache-clear
#     displayName: 'Run pytest with coverage'
#     env:
#       # Temporarily Use Azure SQL Database connection string for testing purposes since Docker takes too long to install & start in MacOS
#       DB_CONNECTION_STRING: $(AZURE_CONNECTION_STRING)
#       # DB_CONNECTION_STRING: 'Driver=ODBC Driver 18 for SQL Server;Server=localhost;Database=master;Uid=SA;Pwd=$(DB_PASSWORD);TrustServerCertificate=yes'
#       DB_PASSWORD: $(DB_PASSWORD)
#   - task: PublishTestResults@2
#     condition: succeededOrFailed()
#     inputs:
#       testResultsFiles: '**/test-results.xml'
#       testRunTitle: 'Publish pytest results on macOS'

#   - task: PublishCodeCoverageResults@1
#     inputs:
#       codeCoverageTool: 'Cobertura'
#       summaryFileLocation: 'coverage.xml'
#     displayName: 'Publish code coverage results'

# Pipeline name shown in ADO UI
name: build-whl-pipeline

# Trigger the pipeline on changes to the main branch & on pull requests
trigger:
  branches:
    include:
      - main

# Trigger on pull requests targeting the main branch
pr:
  branches:
    include:
      - main  

jobs:
- job: BuildWindowsWheels
  # Use the latest Windows image for building
  pool:
    vmImage: 'windows-latest'
  displayName: 'Build -'
  # Strategy matrix to build all combinations
  strategy:
    matrix:
      # Python 3.10 (only x64)
      py310_x64:
        pythonVersion: '3.10'       # Host Python version
        shortPyVer: '310'           # Used in filenames like cp310
        architecture: 'x64'         # Host Python architecture
        targetArch: 'x64'           # Target architecture to pass to build.bat

      # Python 3.11
      py311_x64:
        pythonVersion: '3.11'       # Host Python version
        shortPyVer: '311'           # Used in filenames like cp311
        architecture: 'x64'         # Host Python architecture
        targetArch: 'x64'           # Target architecture to pass to build.bat
      py311_arm64:
        pythonVersion: '3.11'
        shortPyVer: '311'
        architecture: 'x64'         # No arm64 Python, use x64 host
        targetArch: 'arm64'

      # Python 3.12
      py312_x64:
        pythonVersion: '3.12'
        shortPyVer: '312'
        architecture: 'x64'
        targetArch: 'x64'
      py312_arm64:
        pythonVersion: '3.12'
        shortPyVer: '312'
        architecture: 'x64'
        targetArch: 'arm64'

      # Python 3.13
      py313_x64:
        # TODO: Remove this once Python 3.13.5 is available in ADO
        pythonVersion: '3.13.5'
        shortPyVer: '313'
        architecture: 'x64'
        targetArch: 'x64'
      py313_arm64:
        # TODO: Remove this once Python 3.13.5 is available in ADO
        pythonVersion: '3.13.5'
        shortPyVer: '313'
        architecture: 'x64'
        targetArch: 'arm64'

  steps:
    # Use correct Python version and architecture for the current job
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
        architecture: '$(architecture)'
        addToPath: true
      displayName: 'Use Python $(pythonVersion) ($(architecture))'

    # Install required packages: pip, CMake, pybind11
    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install cmake pybind11
      displayName: 'Install dependencies'

    - task: DownloadPipelineArtifact@2
      condition: eq(variables['targetArch'], 'arm64')
      inputs:
        buildType: 'specific'
        project: '$(System.TeamProject)'
        definition: 2162
        buildVersionToDownload: 'latest'
        artifactName: 'mssql-python-arm64-libs'
        targetPath: '$(Build.SourcesDirectory)\mssql_python\pybind\python_libs\arm64'
      displayName: 'Download ARM64 Python libs from latest successful run on branches'

    # Build the PYD file by calling build.bat
    - script: |
        echo "Python Version: $(pythonVersion)"
        echo "Short Tag: $(shortPyVer)"
        echo "Architecture: Host=$(architecture), Target=$(targetArch)"

        cd "$(Build.SourcesDirectory)\mssql_python\pybind"

        REM Optional: override lib path if building for ARM64 since we cannot install arm64 python on x64 host
        if "$(targetArch)"=="arm64" (
          echo Using arm64-specific Python library...
          set CUSTOM_PYTHON_LIB_DIR=$(Build.SourcesDirectory)\mssql_python\pybind\python_libs\arm64
        )

        REM Call build.bat to build the PYD file
        call build.bat $(targetArch)

        REM Calling keep_single_arch.bat to remove ODBC libs of other architectures
        call keep_single_arch.bat $(targetArch)

        cd ..\..
      displayName: 'Build PYD for $(targetArch)'        
      
    # Copy the built .pyd file to staging folder for artifacts
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)\mssql_python\pybind\build\$(targetArch)\py$(shortPyVer)\Release'
        Contents: 'ddbc_bindings.cp$(shortPyVer)-*.pyd'
        TargetFolder: '$(Build.ArtifactStagingDirectory)\all-pyds'
      displayName: 'Place PYD file into artifacts directory'

    # Copy the built .pdb files to staging folder for artifacts
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)\mssql_python\pybind\build\$(targetArch)\py$(shortPyVer)\Release'
        Contents: 'ddbc_bindings.cp$(shortPyVer)-*.pdbs'
        TargetFolder: '$(Build.ArtifactStagingDirectory)\all-pdbs'
      displayName: 'Place PDB file into artifacts directory'

    # Build wheel package for the current architecture
    - script: |
        python -m pip install --upgrade pip
        pip install wheel setuptools
        set ARCHITECTURE=$(targetArch)
        python setup.py bdist_wheel
      displayName: 'Build wheel package for Python $(pythonVersion) ($(targetArch))'
    
    # Copy the wheel file to the artifacts
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)\dist'
        Contents: '*.whl'
        TargetFolder: '$(Build.ArtifactStagingDirectory)\dist'
      displayName: 'Collect wheel package'    

    # Publish the collected .pyd file(s) as build artifacts
    - task: PublishBuildArtifacts@1
      condition: succeededOrFailed()
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)\all-pyds'
        ArtifactName: 'mssql-python-pyds'
        publishLocation: 'Container'
      displayName: 'Publish all PYDs as artifacts'

    # Publish the python arm64 libraries as build artifacts for next builds if ARM64
    - task: PublishBuildArtifacts@1
      condition: eq(variables['targetArch'], 'arm64')
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\mssql_python\pybind\python_libs\arm64'
        ArtifactName: 'mssql-python-arm64-libs'
        publishLocation: 'Container'
      displayName: 'Publish arm64 libs as artifacts'
    
    # Publish the collected wheel file(s) as build artifacts
    - task: PublishBuildArtifacts@1
      condition: succeededOrFailed()
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)\dist'
        ArtifactName: 'mssql-python-wheels-dist'
        publishLocation: 'Container'
      displayName: 'Publish all wheels as artifacts'

- job: BuildMacOSWheels
  # Use the latest macOS image for building
  pool:
    vmImage: 'macos-latest'
  # Display name for the job in Azure DevOps UI
  displayName: 'Build macOS - '
  strategy:
    matrix:
      # Python 3.10-3.13 (only x86_64)
      py310_x86_64:
        pythonVersion: '3.10'
        shortPyVer: '310'
        architecture: 'x86_64'
        targetArch: 'x86_64'
      py311_x86_64:
        pythonVersion: '3.11'
        shortPyVer: '311'
        architecture: 'x86_64'
        targetArch: 'x86_64'
      py312_x86_64:
        pythonVersion: '3.12'
        shortPyVer: '312'
        architecture: 'x86_64'
        targetArch: 'x86_64'
      py313_x86_64:
        pythonVersion: '3.13'
        shortPyVer: '313'
        architecture: 'x86_64'
        targetArch: 'x86_64'
  steps:
    # Use correct Python version and architecture for the current job
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
        architecture: '$(architecture)'
        addToPath: true
      displayName: 'Use Python $(pythonVersion) ($(architecture))'

    # Install CMake on macOS
    - script: |
        brew update
        brew install cmake
      displayName: 'Install CMake'

    # Install required packages: pip, CMake, pybind11
    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install cmake pybind11
      displayName: 'Install dependencies'

    # Build the .so file by calling build.sh
    - script: |
        echo "Python Version: $(pythonVersion)"
        echo "Short Tag: $(shortPyVer)"
        echo "Architecture: Host=$(architecture), Target=$(targetArch)"
        cd "$(Build.SourcesDirectory)/mssql_python/pybind"
        # Call build.sh to build the .so file
        ./build.sh $(targetArch)
      displayName: 'Build .so file'

    # Copy the built .so file to staging folder for artifacts
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/mssql_python/pybind/build/$(targetArch)/py$(shortPyVer)/Release'
        Contents: 'ddbc_bindings.cp$(shortPyVer)-*.so'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/all-pyds'
      displayName: 'Place .so file into artifacts directory'
    
    # Build wheel package for the current architecture
    - script: |
        python -m pip install --upgrade pip
        pip install wheel setuptools
        set ARCHITECTURE=$(targetArch)
        python setup.py bdist_wheel
      displayName: 'Build wheel package for Python $(pythonVersion) ($(targetArch))'
    
    # Copy the wheel file to the artifacts
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/dist'
        Contents: '*.whl'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/dist'
      displayName: 'Collect wheel package'
    
    # Publish the collected .so file(s) as build artifacts
    - task: PublishBuildArtifacts@1
      condition: succeededOrFailed()
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/all-pyds'
        ArtifactName: 'mssql-python-pyds'
        publishLocation: 'Container'
      displayName: 'Publish all .so files as artifacts'
    
    # Publish the collected wheel file(s) as build artifacts
    - task: PublishBuildArtifacts@1
      condition: succeededOrFailed()
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/dist'
        ArtifactName: 'mssql-python-wheels-dist'
        publishLocation: 'Container'
      displayName: 'Publish all wheels as artifacts'
