name: pr-validation-pipeline

# Trigger the pipeline on merge to main branch
trigger:
  branches:
    include:
      - main

# Trigger on pull requests targeting the main branch
pr:
  branches:
    include:
      - main  

jobs:
- job: BuildLinuxWheels
  # Use the latest Ubuntu image for building
  pool:
    vmImage: 'ubuntu-latest'

  steps:
    # Use Python 3.12
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.12'
        addToPath: true
      displayName: 'Use Python 3.12'

    # Install system dependencies
    - script: |
        sudo apt-get update
        sudo apt-get install -y unixodbc-dev cmake build-essential
      displayName: 'Install system dependencies'

    # Install Python dependencies
    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install cmake pybind11 wheel setuptools
      displayName: 'Install Python dependencies'

    # Build native extension
    - script: |
        cd mssql_python/pybind
        chmod +x build.sh
        ./build.sh
        ls -la ../ddbc_bindings.*.so
      displayName: 'Build pybind bindings (.so)'

    # Run main.py
    - script: |
        python main.py
        echo $(DB_CONNECTION_STRING:0:20)
      displayName: 'Run main.py'
      env:
        DB_CONNECTION_STRING: $(AZURE_CONNECTION_STRING)
