# GitHub-to-ADO Sync Pipeline
# Syncs main branch from public GitHub to internal Azure DevOps daily at 5pm IST

name: GitHub-Sync-$(Date:yyyyMMdd)$(Rev:.r)

schedules:
  - cron: "30 11 * * *"
    displayName: "Daily sync at 5pm IST"
    branches:
      include:
        - main
    always: true

trigger: none
pr: none

jobs:
- job: SyncFromGitHub
  displayName: 'Sync main branch from GitHub'
  pool:
    vmImage: 'windows-latest'
  
  steps:
  - checkout: self
    persistCredentials: true

  - task: CmdLine@2
    displayName: 'Add GitHub remote'
    inputs:
      script: |
        git remote add github https://github.com/microsoft/mssql-python.git
        git fetch github main

  - task: CmdLine@2
    displayName: 'Create timestamped sync branch'
    inputs:
      script: |
        echo Getting current timestamp...
        powershell -Command "Get-Date -Format 'yyyyMMdd-HHmmss'" > timestamp.txt
        set /p TIMESTAMP=<timestamp.txt
        set SYNC_BRANCH=github-sync-%TIMESTAMP%
        echo %SYNC_BRANCH% > branchname.txt
        echo Creating sync branch: %SYNC_BRANCH%
        git checkout -b %SYNC_BRANCH%
        echo ##vso[task.setvariable variable=SYNC_BRANCH;isOutput=true]%SYNC_BRANCH%

  - task: CmdLine@2
    displayName: 'Sync with GitHub main'
    inputs:
      script: |
        echo Attempting to pull from GitHub...
        git config user.email "sync@microsoft.com"
        git config user.name "ADO Sync Bot"
        
        git pull github main --no-rebase || (
          echo Merge conflicts detected. Using GitHub version as source of truth...
          git rm -rf .
          git checkout github/main -- .
          git -c user.email="sync@microsoft.com" -c user.name="ADO Sync Bot" commit -m "Sync: Resolve conflicts by accepting GitHub main as source of truth"
        )

  - task: CmdLine@2
    displayName: 'Push branch to Azure DevOps'
    inputs:
      script: |
        set /p SYNC_BRANCH=<branchname.txt
        echo Pushing branch: %SYNC_BRANCH%
        
        git config user.email "sync@microsoft.com"
        git config user.name "ADO Sync Bot"
        
        git push origin %SYNC_BRANCH% --set-upstream
        
        if %ERRORLEVEL% EQU 0 (
          echo Branch pushed successfully!
        ) else (
          echo ERROR: Push failed!
          exit /b 1
        )

  - task: CmdLine@2
    displayName: 'Create pull request'
    inputs:
      script: |
        echo Installing Azure DevOps extension...
        call az extension add --name azure-devops --only-show-errors
        
        echo Setting up authentication...
        set AZURE_DEVOPS_EXT_PAT=$(System.AccessToken)
        
        echo Configuring Azure DevOps defaults...
        call az devops configure --defaults organization=https://sqlclientdrivers.visualstudio.com project=mssql-python
        
        set /p SYNC_BRANCH=<branchname.txt
        echo Creating PR from branch: %SYNC_BRANCH% to main
        
        call az repos pr create --source-branch %SYNC_BRANCH% --target-branch main --title "ADO-GitHub Sync - %date%" --description "Automated sync from GitHub main branch" --auto-complete true --squash true --delete-source-branch true --output table
        
        if %ERRORLEVEL% EQU 0 (
          echo PR created successfully!
          echo Adding reviewers...
          call az repos pr list --source-branch %SYNC_BRANCH% --target-branch main --status active --output tsv --query "[0].pullRequestId" > pr_id.txt
          set /p PR_ID=<pr_id.txt
          call az repos pr reviewer add --id %PR_ID% --reviewers gargsaumya@microsoft.com sharmag@microsoft.com sumit.sarabhai@microsoft.com jathakkar@microsoft.com spaitandi@microsoft.com --output table
          if %ERRORLEVEL% EQU 0 (
            echo Reviewers added successfully!
          )
          del pr_id.txt
        ) else (
          echo ERROR: Failed to create PR
          exit /b 1
        )
        
        if exist timestamp.txt del timestamp.txt
        if exist branchname.txt del branchname.txt
